name: patrick
favicon: null
layout_spectrum: 1
typography_spectrum: 0.386973308166489
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b0914e'
    - '#b9b0a1'
    - '#8e703c'
    - '#180e0f'
    - '#40480c'
  brandStrength: 0.031388651579618454
  lightness: 0.6485669780522585
  saturation: 0.13777959626168013
  rhythmicContrast: 0.6813965456094593
purpose: []
